import 'dart:io';

void main() {
  final Directory dir = Directory('lib');
  if (!dir.existsSync()) return;

  int setStateCount = 0;
  int valueNotifierCount = 0;
  int repaintBoundaryCount = 0;
  int transactionCount = 0;
  int incrementCount = 0;
  final List<String> thoughts = <String>[];

  for (final FileSystemEntity entity in dir.listSync(recursive: true)) {
    if (entity is File && entity.path.endsWith('.dart')) {
      try {
        final List<String> lines = entity.readAsLinesSync();
        for (int i = 0; i < lines.length; i++) {
          final String line = lines[i].trim();

          if (line.contains('setState(')) setStateCount++;
          if (line.contains('ValueNotifier')) valueNotifierCount++;
          if (line.contains('RepaintBoundary')) repaintBoundaryCount++;
          if (line.contains('runTransaction') ||
              line.contains('Transaction(')) transactionCount++;
          if (line.contains('FieldValue.increment')) incrementCount++;

          if (line.contains('// @AETHER:')) {
            thoughts.add(
              '- **${entity.uri.pathSegments.last}** (Line ${i + 1}): '
              '${line.substring(line.indexOf('// @AETHER:') + 11).trim()}',
            );
          }
        }
      } catch (_) {
        // Skip files with encoding issues
      }
    }
  }

  final File telemetryFile = File('AETHER_TELEMETRY.md');
  final StringBuffer output =
      StringBuffer('# Aether Automated Telemetry Report\n\n');
  output.writeln('> Auto-generated by the pre-commit Flight Recorder.\n');

  output.writeln('## 1. Architectural Fingerprint');
  if (transactionCount > 0 || incrementCount > 0) {
    output.writeln(
      'PASS: Atomic operations detected '
      '(runTransaction: $transactionCount, increment: $incrementCount)',
    );
  } else {
    output.writeln('FAIL: No atomic operations detected.');
  }

  output.writeln('\n### UI Performance');
  output.writeln(
    'setState: $setStateCount | '
    'ValueNotifier: $valueNotifierCount | '
    'RepaintBoundary: $repaintBoundaryCount',
  );

  if (valueNotifierCount > 0 || repaintBoundaryCount > 0) {
    output.writeln('PASS: Targeted repaints detected.');
  } else if (setStateCount > 3) {
    output.writeln('WARNING: High setState usage without localized rebuilds.');
  }

  output.writeln('\n## 2. Developer Thought Log');
  if (thoughts.isNotEmpty) {
    thoughts.forEach(output.writeln);
  } else {
    output.writeln('No inline @AETHER: comments found.');
  }

  try {
    telemetryFile.writeAsStringSync(output.toString());
  } catch (_) {
    // Failsafe
  }
}
