import 'dart:io';

void main() async {
  print('===================================================');
  print('Aether Environment Setup');
  print('===================================================');

  // 1. Validate Root Directory
  final File pubspec = File('pubspec.yaml');
  if (!pubspec.existsSync()) {
    print('ERROR: pubspec.yaml not found.');
    print('HEALING ACTION: Run this from your Flutter project root.');
    exit(1);
  }

  // 2. Inject Required Dependencies
  print('Checking testing & linting dependencies...');
  final String pubspecContent = pubspec.readAsStringSync();
  final List<String> missingDeps = <String>[];

  if (!pubspecContent.contains('fake_cloud_firestore:')) {
    missingDeps.add('fake_cloud_firestore');
  }
  if (!pubspecContent.contains('flutter_lints:')) {
    missingDeps.add('flutter_lints');
  }

  if (missingDeps.isNotEmpty) {
    print('Injecting missing dev_dependencies: ${missingDeps.join(', ')}...');
    final ProcessResult result = await Process.run('flutter', <String>[
      'pub',
      'add',
      '--dev',
      ...missingDeps,
    ], runInShell: true);
    if (result.exitCode != 0) {
      print('ERROR: Failed to add dependencies. Please add them manually.');
      print(result.stderr);
    } else {
      print('Dependencies injected successfully.');
    }
  } else {
    print('All necessary dev_dependencies are present.');
  }

  // 3. Ensure Git is present and healthy
  final Directory hookDir = Directory('.git/hooks');
  if (!hookDir.existsSync()) {
    print('No .git directory found. Initializing git...');
    final ProcessResult gitInit = await Process.run('git', <String>[
      'init',
    ], runInShell: true);
    if (gitInit.exitCode != 0) {
      print('ERROR: Git is not installed or accessible.');
      print(
        'HEALING ACTION: Install Git, run git init, and re-run this script.',
      );
      exit(1);
    }
    hookDir.createSync(recursive: true);
  }

  // 4. Generate the robust compiler script
  _generateCompilerScript();

  // 5. Safely Append to pre-commit hook
  final File hookFile = File('.git/hooks/pre-commit');
  const String hookCommand =
      'dart aether_compiler.dart\ngit add AETHER_TELEMETRY.md';

  if (hookFile.existsSync()) {
    final String currentHook = hookFile.readAsStringSync();
    if (!currentHook.contains('aether_compiler.dart')) {
      print('Appending Aether telemetry to existing pre-commit hook...');
      hookFile.writeAsStringSync(
        '\n# Aether Telemetry\n$hookCommand\n',
        mode: FileMode.append,
      );
    }
  } else {
    print('Creating new pre-commit hook...');
    hookFile.writeAsStringSync('#!/bin/sh\n# Aether Telemetry\n$hookCommand\n');
  }

  if (!Platform.isWindows) {
    await Process.run('chmod', <String>['+x', '.git/hooks/pre-commit']);
  }

  print('SETUP COMPLETE. The Aether Flight Recorder is active.');
  print('You can now write code normally.');
  print('===================================================');
}

void _generateCompilerScript() {
  const String compilerCode = r'''
import 'dart:io';

void main() {
  final Directory dir = Directory('lib');
  if (!dir.existsSync()) return;

  int setStateCount = 0;
  int valueNotifierCount = 0;
  int repaintBoundaryCount = 0;
  int transactionCount = 0;
  int incrementCount = 0;
  final List<String> thoughts = <String>[];

  for (final FileSystemEntity entity in dir.listSync(recursive: true)) {
    if (entity is File && entity.path.endsWith('.dart')) {
      try {
        final List<String> lines = entity.readAsLinesSync();
        for (int i = 0; i < lines.length; i++) {
          final String line = lines[i].trim();

          if (line.contains('setState(')) setStateCount++;
          if (line.contains('ValueNotifier')) valueNotifierCount++;
          if (line.contains('RepaintBoundary')) repaintBoundaryCount++;
          if (line.contains('runTransaction') ||
              line.contains('Transaction(')) transactionCount++;
          if (line.contains('FieldValue.increment')) incrementCount++;

          if (line.contains('// @AETHER:')) {
            thoughts.add(
              '- **${entity.uri.pathSegments.last}** (Line ${i + 1}): '
              '${line.substring(line.indexOf('// @AETHER:') + 11).trim()}',
            );
          }
        }
      } catch (_) {
        // Skip files with encoding issues
      }
    }
  }

  final File telemetryFile = File('AETHER_TELEMETRY.md');
  final StringBuffer output =
      StringBuffer('# Aether Automated Telemetry Report\n\n');
  output.writeln('> Auto-generated by the pre-commit Flight Recorder.\n');

  output.writeln('## 1. Architectural Fingerprint');
  if (transactionCount > 0 || incrementCount > 0) {
    output.writeln(
      'PASS: Atomic operations detected '
      '(runTransaction: $transactionCount, increment: $incrementCount)',
    );
  } else {
    output.writeln('FAIL: No atomic operations detected.');
  }

  output.writeln('\n### UI Performance');
  output.writeln(
    'setState: $setStateCount | '
    'ValueNotifier: $valueNotifierCount | '
    'RepaintBoundary: $repaintBoundaryCount',
  );

  if (valueNotifierCount > 0 || repaintBoundaryCount > 0) {
    output.writeln('PASS: Targeted repaints detected.');
  } else if (setStateCount > 3) {
    output.writeln('WARNING: High setState usage without localized rebuilds.');
  }

  output.writeln('\n## 2. Developer Thought Log');
  if (thoughts.isNotEmpty) {
    thoughts.forEach(output.writeln);
  } else {
    output.writeln('No inline @AETHER: comments found.');
  }

  try {
    telemetryFile.writeAsStringSync(output.toString());
  } catch (_) {
    // Failsafe
  }
}
''';

  File('aether_compiler.dart').writeAsStringSync(compilerCode);
}
